import type { RawRow } from './file-parser';

/**
 * A saved mapping profile that defines how source columns map to internal schema fields.
 * Profiles are created during the first upload of a new source format and reused for
 * subsequent uploads from the same source.
 */
export interface MappingProfile {
  /** Unique identifier for this mapping profile */
  id: string;
  /** Human-readable name (e.g., "BirchStreet PO Export") */
  name: string;
  /** Source system identifier (e.g., "birchstreet", "micros") */
  sourceSystem: string;
  /** Column-to-field mappings: key = source column name, value = target schema field */
  mappings: Record<string, string>;
  /** Optional transformations to apply after mapping (e.g., date format conversion) */
  transforms?: Record<string, string>;
  /** Timestamp when this profile was created */
  createdAt?: string;
  /** Timestamp when this profile was last updated */
  updatedAt?: string;
}

/**
 * A row that has been mapped from source column names to internal schema field names.
 */
export type MappedRow = Record<string, unknown>;

/**
 * A suggested column mapping with a confidence score, generated by analyzing
 * source headers against known target field names.
 */
export interface SuggestedMapping {
  /** The original column name from the source file */
  sourceColumn: string;
  /** The suggested internal schema field name */
  targetField: string;
  /** Confidence score from 0 to 1 (1 = exact match, lower = fuzzy match) */
  confidence: number;
}

/**
 * FieldMapper handles mapping raw parsed rows from source file columns
 * to the internal Spotlight schema fields. Supports saved mapping profiles
 * for known source systems and can suggest mappings for new formats.
 */
export class FieldMapper {
  private profile: MappingProfile | null;

  /**
   * Create a new FieldMapper, optionally with an existing mapping profile.
   *
   * @param profile - An existing mapping profile to use for mapping
   */
  constructor(profile?: MappingProfile) {
    this.profile = profile ?? null;
  }

  /**
   * Set or replace the current mapping profile.
   *
   * @param profile - The mapping profile to use for subsequent mapping operations
   */
  setProfile(profile: MappingProfile): void {
    this.profile = profile;
  }

  /**
   * Map a single raw row using the current mapping profile.
   *
   * TODO: Implement row mapping that:
   * - Applies column name mappings from the profile
   * - Applies any configured transforms (date parsing, unit conversion, etc.)
   * - Handles missing source columns gracefully (set target field to null)
   * - Preserves unmapped columns in a special "_unmapped" key for review
   * - Trims string values
   *
   * @param row - A raw row from the file parser
   * @returns The mapped row with internal schema field names
   * @throws Error if no mapping profile is set
   */
  mapRow(row: RawRow): MappedRow {
    if (!this.profile) {
      throw new Error('No mapping profile set. Call setProfile() or pass a profile to the constructor.');
    }

    // TODO: Apply transforms (date parsing, number formatting, unit conversion)
    // TODO: Handle case-insensitive column matching
    // TODO: Collect unmapped columns for review
    const mapped: MappedRow = {};
    const { mappings } = this.profile;

    for (const [sourceColumn, targetField] of Object.entries(mappings)) {
      const value = row[sourceColumn];
      mapped[targetField] = value !== undefined ? value : null;
    }

    return mapped;
  }

  /**
   * Map all rows using the current mapping profile.
   *
   * TODO: Implement batch mapping with:
   * - Progress callback for large datasets
   * - Error collection (don't fail on individual row errors)
   * - Performance optimization for large files (>100k rows)
   *
   * @param rows - Array of raw rows from the file parser
   * @returns Array of mapped rows with internal schema field names
   */
  mapAll(rows: RawRow[]): MappedRow[] {
    // TODO: Add progress callback support for UI progress bars
    // TODO: Add batch processing for memory efficiency on large files
    // TODO: Collect and return mapping errors per row
    return rows.map((row) => this.mapRow(row));
  }

  /**
   * Analyze source file headers and suggest mappings to target schema fields.
   * Uses fuzzy matching, common aliases, and source system presets to generate
   * suggestions with confidence scores.
   *
   * TODO: Implement smart mapping suggestions using:
   * - Exact string matching (confidence: 1.0)
   * - Case-insensitive matching (confidence: 0.95)
   * - Common aliases (e.g., "qty" -> "quantity", "amt" -> "amount") (confidence: 0.85)
   * - Substring matching (e.g., "item_description" contains "description") (confidence: 0.7)
   * - Levenshtein distance for fuzzy matching (confidence: varies)
   * - Source system presets for known formats (confidence: 0.9)
   *
   * @param headers - Column headers from the source file
   * @param targetFields - Internal schema field names to map to
   * @returns Array of suggested mappings sorted by confidence (highest first)
   */
  getSuggestedMappings(headers: string[], targetFields: string[]): SuggestedMapping[] {
    // TODO: Implement Levenshtein distance calculation for fuzzy matching
    // TODO: Load common aliases from source-presets.ts
    // TODO: Support source system detection to use preset mappings
    // TODO: Handle duplicate suggestions (same source -> multiple targets)
    const suggestions: SuggestedMapping[] = [];

    for (const header of headers) {
      const normalizedHeader = header.toLowerCase().trim().replace(/[\s_-]+/g, '_');

      for (const targetField of targetFields) {
        const normalizedTarget = targetField.toLowerCase().trim().replace(/[\s_-]+/g, '_');

        let confidence = 0;

        // Exact match
        if (normalizedHeader === normalizedTarget) {
          confidence = 1.0;
        }
        // Contains match
        else if (
          normalizedHeader.includes(normalizedTarget) ||
          normalizedTarget.includes(normalizedHeader)
        ) {
          confidence = 0.7;
        }

        if (confidence > 0) {
          suggestions.push({
            sourceColumn: header,
            targetField,
            confidence,
          });
        }
      }
    }

    // Sort by confidence descending
    return suggestions.sort((a, b) => b.confidence - a.confidence);
  }
}
